package ie.gmit.sw.breaker;


/**
* ie/gmit/sw/breaker/_CORBAVigenereBreakerStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from VigenereBreaker.idl
* Saturday, December 12, 2015 5:03:44 PM GMT
*/

public class _CORBAVigenereBreakerStub extends org.omg.CORBA.portable.ObjectImpl implements ie.gmit.sw.breaker.CORBAVigenereBreaker
{

  public String decrypt (String cypherText, int maxKeyLength)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("decrypt", true);
                $out.write_string (cypherText);
                $out.write_long (maxKeyLength);
                $in = _invoke ($out);
                String $result = $in.read_string ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return decrypt (cypherText, maxKeyLength        );
            } finally {
                _releaseReply ($in);
            }
  } // decrypt

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:ie/gmit/sw/breaker/CORBAVigenereBreaker:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _CORBAVigenereBreakerStub
