package ie.gmit.sw.breaker;


/**
* ie/gmit/sw/breaker/CORBAVigenereBreakerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from VigenereBreaker.idl
* Saturday, December 12, 2015 5:03:44 PM GMT
*/

public interface CORBAVigenereBreakerOperations 
{
  String decrypt (String cypherText, int maxKeyLength);
} // interface CORBAVigenereBreakerOperations
