package ie.gmit.sw.breaker;



/**
* ie/gmit/sw/breaker/CORBAVigenereBreakerHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from VigenereBreaker.idl
* Saturday, December 12, 2015 5:03:44 PM GMT
*/

abstract public class CORBAVigenereBreakerHelper
{
  private static String  _id = "IDL:ie/gmit/sw/breaker/CORBAVigenereBreaker:1.0";

  public static void insert (org.omg.CORBA.Any a, ie.gmit.sw.breaker.CORBAVigenereBreaker that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static ie.gmit.sw.breaker.CORBAVigenereBreaker extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (ie.gmit.sw.breaker.CORBAVigenereBreakerHelper.id (), "CORBAVigenereBreaker");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static ie.gmit.sw.breaker.CORBAVigenereBreaker read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_CORBAVigenereBreakerStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, ie.gmit.sw.breaker.CORBAVigenereBreaker value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static ie.gmit.sw.breaker.CORBAVigenereBreaker narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof ie.gmit.sw.breaker.CORBAVigenereBreaker)
      return (ie.gmit.sw.breaker.CORBAVigenereBreaker)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      ie.gmit.sw.breaker._CORBAVigenereBreakerStub stub = new ie.gmit.sw.breaker._CORBAVigenereBreakerStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static ie.gmit.sw.breaker.CORBAVigenereBreaker unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof ie.gmit.sw.breaker.CORBAVigenereBreaker)
      return (ie.gmit.sw.breaker.CORBAVigenereBreaker)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      ie.gmit.sw.breaker._CORBAVigenereBreakerStub stub = new ie.gmit.sw.breaker._CORBAVigenereBreakerStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
