package ie.gmit.sw.breaker;



/**
* ie/gmit/sw/breaker/CORBAVigenereBreaker.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from VigenereBreaker.idl
* Saturday, December 12, 2015 5:03:44 PM GMT
*/

public interface CORBAVigenereBreaker extends CORBAVigenereBreakerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface CORBAVigenereBreaker
